spring:
  datasource:
    url: jdbc:mysql://123.56.242.139:3306/springboot_db?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 123456
    type: com.zaxxer.hikari.util.DriverDataSource
